### ISSUE TITLE
EnumFormatter.formatEnum throws a NoSuchElementException

### ISSUE THREAD

**Issue by pbarron** [doriordan/skuber#190]
Noticed this while completing #181. When parsing an empty Json object the following exceptions is thrown 

```
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:349)
	at scala.None$.get(Option.scala:347)
	at skuber.json.format.package$EnumFormatter.$anonfun$formatEnum$3(package.scala:87)
	at scala.Option.getOrElse(Option.scala:121)
	at skuber.json.format.package$EnumFormatter.$anonfun$formatEnum$1(package.scala:87)
	at play.api.libs.json.JsSuccess.map(JsResult.scala:18)
	at play.api.libs.json.OFormat$$anon$5.$anonfun$inmap$1(Format.scala:29)
	at play.api.libs.json.OFormat$$anon$1.reads(Format.scala:37)
	at play.api.libs.json.Reads.$anonfun$map$1(Reads.scala:43)
	at play.api.libs.json.Reads$$anon$8.reads(Reads.scala:132)
	at play.api.libs.json.Reads$$anon$3$$anon$4.reads(Reads.scala:110)
	at play.api.libs.json.OFormat$$anon$2.reads(Format.scala:44)
...
```
instead of returning a JsError. The issue seems to be [here](https://github.com/doriordan/skuber/blob/master/client/src/main/scala/skuber/json/package.scala#L87
) where a `get` on the default optional value is made.

**Comment by doriordan** [comment]
Thanks @pbarronfor the bug report, so  this looks like it will be thrown if no default is supplied by the applicable Json formatter but the field is missing, in this case no value can be returned. 
At first glance I think the best solution might be to split `formatEnum` into two different functions - one (`formatEnumWithDefault`) has a mandatory default value parameter and the other  (`formatEnum`) has no default parameter. `formatNullable` can be used with the first, knowing there is always a default to fall back on if it is missing, and the non-nullable variation of`format` can be used with the second to automatically get a normal JsError if the value is missing.

**Comment by pbarron** [comment]
> so this looks like it will be thrown if no default is supplied by the applicable Json formatter but the field is missing, in this case no value can be returned.

Yes that is correct. 

The solution you are suggesting should work. Though, probably also need to review the usages of the function where default is None to determine if the field needs to changed to an "Option" or left as is and return a JSError.
