### ISSUE TITLE
recommendation for running skuber web svc in pod

### ISSUE THREAD

**Issue by Matt-Dee** [doriordan/skuber#234]
I am currently trying to spin up a container within kubernetes that contains a webservice that is powered by skuber.

All of this is running within a k8s cluster that is being coordinated by Rancher.

I currently grab the rancher .kube/config that is available in the web application and store it in a config map.  The config map then maps to ./kube/config in the skuber webservice image.

When I run the application and try to call the k8s api with skuber, I get this by default.
```
[ERROR] [10/17/2018 12:27:28.943] [default-akka.actor.default-dispatcher-4] [skuber.api] [ { reqId=a6dc5b5d-a72d-4619-8f46-a0da7f785098} } - HTTP request resulted in an unexpected exception ] (akka.stream.ConnectionException: Hostname verification failed! Expected session to be for spackler)

192.168.88.135 - - [17/Oct/2018:12:27:28 +0000] "GET /workflow/submit-ll-workflow/hadoop/0.05/0.90/ HTTP/1.1" 500 110 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:62.0) Gecko/20100101 Firefox/62.0" 103
```

That is with the following setting:
```
insecure-skip-tls-verify: true
```

I then tried to get around this error by using the following property:
```
 -Dssl-config.loose.acceptAnyCertificate=true
```

I now get this error:
```
[INFO] [10/18/2018 19:07:34.579] [dw-17 - GET /workflow/submit-ll-workflow/hadoop/0.05/0.90] [skuber.api] [ { reqId=ec659fef-6219-43f3-8e12-8ddeb9c39040} } - about to send HTTP request: POST https://spackler/k8s/clusters/c-d7x88/api/v1/namespaces/default/pods]

[ERROR] [10/18/2018 19:07:35.060] [default-akka.actor.default-dispatcher-3] [skuber.api] [ { reqId=ec659fef-6219-43f3-8e12-8ddeb9c39040} } - HTTP request resulted in an unexpected exception ] (akka.stream.StreamTcpException: Connection failed.)

ERROR [2018-10-18 19:07:35,062] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: c1a1568628d70b03

! akka.stream.StreamTcpException: Connection failed.

DEBUG [2018-10-18 19:07:35,089] org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor: org.eclipse.jetty.server.handler.gzip.GzipHttpOutputInterceptor@33ed7734 exclude by status 500

DEBUG [2018-10-18 19:07:35,090] org.eclipse.jetty.server.HttpChannel: sendResponse info=null content=HeapByteBuffer@673e32cc[p=0,l=110,c=8192,r=110]={<<<{"code":500,"mess...68628d70b03)."}>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00} complete=true committing=true callback=Blocker@3e548994{null}

DEBUG [2018-10-18 19:07:35,090] org.eclipse.jetty.server.HttpChannel: COMMIT for /workflow/submit-ll-workflow/hadoop/0.05/0.90 on HttpChannelOverHttp@445003db{r=1,c=true,a=DISPATCHED,uri=http://wrkflw.svc.cmdaa/workflow/submit-ll-workflow/hadoop/0.05/0.90}

500 Internal Server Error HTTP/1.1

Connection: close

Date: Thu, 18 Oct 2018 19:07:33 GMT

Content-Length: 110

Content-Type: application/json
```

ANY guidance would be greatly appreciated.

**Comment by Matt-Dee** [comment]
I'll also mention this.  The skuber docker image is mapped to an ingress within k8s at wrkflw.svc.cmdaa

**Comment by Matt-Dee** [comment]
Is there an example of making requests using RBAC?

**Comment by doriordan** [comment]
Hi @Matt-Dee 
I don;t really know Rancher but generally if you are running an application that uses Skuber inside a Pod you can use in-cluster config, something like:
```
import skuber._
import skuber.api.Configuration
...
val k8s = k8sInit(k8Configuration.inClusterConfig.get)
```
In terms of RBAC, I take it you want to add role / role bindings that allow your application to access the required Kubernetes resources - while Skuber supports updating RBAC programmatically, I am guessing you might just want to use `kubectl` to set the permissions? If so, a general guide for that is at https://kubernetes.io/docs/reference/access-authn-authz/rbac/

**Comment by Matt-Dee** [comment]
Yes.  

```
val k8s = k8sInit(Configuration.inClusterConfig.get)
```

This is exactly what I needed.  Every container is guaranteed to contain this information.

Thanks!

**Comment by Matt-Dee** [comment]
It worked.  An example of this(or maybe throw it in a comment in some of the examples) will help others.

Thanks!

**Comment by Matt-Dee** [comment]
@doriordan 

You've been awesome with suggestions and help.  My .inClusterConfig has been working until recently.  All of my rbac rules are still present, but I have been getting  the following error.  I've turned up the logging to debug to see what the problem might be but it hasn't offered much more information.

```
ERROR [2018-11-30 14:25:46,286] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 7d338aff68c4ca10

! java.lang.NoSuchMethodError: com.typesafe.config.Config.getIsNull(Ljava/lang/String;)Z

! at skuber.api.client.package$.getSkuberConfig$1(package.scala:961)

! at skuber.api.client.package$.init(package.scala:976)

! at skuber.api.client.package$.init(package.scala:938)

! at skuber.package$.k8sInit(package.scala:267)

! at org.cmdaa.service.workflow.WorkflowResource.runParamsLogLikeliWorkflow(WorkflowResource.scala:115)

! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

! at java.lang.reflect.Method.invoke(Method.java:498)

! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)

! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)

! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)

! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)

! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)

! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)

! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)

! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)

! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)

! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)

! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)

! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)

! at org.glassfish.jersey.internal.Errors.process(Errors.java:297)

! at org.glassfish.jersey.internal.Errors.process(Errors.java:267)

! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)

! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)

! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)

! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)

! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)

! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)

! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)

! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)

! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)

! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)

! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:34)

! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)

! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:50)

! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:44)

! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)

! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)

! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)

! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)

! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)

! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)

! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)

! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)

! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)

! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)

! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:241)

! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51)

! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:561)

! at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:68)

! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)

! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)

! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)

! at org.eclipse.jetty.server.Server.handle(Server.java:564)

! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)

! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)

! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)

! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)

! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)

! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)

! at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)

! at java.lang.Thread.run(Thread.java:748)
```
Do you know what usually causes this error.  All of the tokens are present in the image.

**Comment by Matt-Dee** [comment]
Nevermind.  Ugh.  Someone committed a dependency that pulled in a later version of typesafe config.
