### ISSUE TITLE
Substream Source cannot be materialized more than once

### ISSUE THREAD

**Issue by cecol** [doriordan/skuber#288]
Hi all
I use `"io.skuber" %% "skuber" % "2.3.0"`  in my project
Sometime my application would fail with followings:
```
[INFO] [09/03/2019 08:22:46.219] [updown-system-akka.actor.default-dispatcher-3] [skuber.api] Using following context for connecting to Kubernetes cluster: Context(Cluster(v1,https://x.x.x.x:443,false,Some(Left(/var/run/secrets/kubernetes.io/serviceaccount/ca.crt))),TokenAuth(token=<redacted>),Namespace(Namespace,v1,ObjectMeta(default,,,,,,None,None,None,Map(),Map(),List(),0,None,None),None,None))
[INFO] [09/03/2019 08:22:55.308] [updown-system-akka.actor.default-dispatcher-3] [skuber.api] [ { reqId=410519fd-5edc-4121-a671-a582cb0aace1} } - about to send HTTP request: GET https://x.x.x.x/api/v1/namespaces/default/pods]
[INFO] [09/03/2019 08:23:01.336] [updown-system-akka.actor.default-dispatcher-3] [skuber.api] [ { reqId=410519fd-5edc-4121-a671-a582cb0aace1} } - received response with HTTP status 200]
[WARN] [09/03/2019 08:23:02.393] [updown-system-akka.actor.default-dispatcher-2] [updown-system/Pool(shared->https://x.x.x.x:443)] [0 (WaitingForResponseEntitySubscription)] Response entity was not subscribed after 1 second. Make sure to read the response entity body or call `discardBytes()` on it. GET /api/v1/namespaces/default/pods Empty -> 200 OK Chunked
[ERROR] [09/03/2019 08:23:02.601] [updown-system-akka.actor.default-dispatcher-4] [akka://updown-system/user/up-down-judge] UpDownController fail
java.lang.IllegalStateException: Substream Source cannot be materialized more than once
        at akka.stream.impl.fusing.SubSource$$anon$4.setCB(StreamOfStreams.scala:756)
        at akka.stream.impl.fusing.SubSource$$anon$4.preStart(StreamOfStreams.scala:766)
        at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:295)
        at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:557)
        at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:679)
        at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:727)
        at akka.actor.Actor.aroundPreStart(Actor.scala:528)
        at akka.actor.Actor.aroundPreStart$(Actor.scala:528)
        at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:670)
        at akka.actor.ActorCell.create(ActorCell.scala:652)
        at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:523)
        at akka.actor.ActorCell.systemInvoke(ActorCell.scala:545)
        at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:283)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
        at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

I try to figure it out with `google` and got this explaination:
https://github.com/akka/akka-http/issues/1447
It seems that the problem is solved by newer `akka-http` version `10.1.8`
But current  `"io.skuber" %% "skuber" % "2.3.0"` is consisted of `akka-http` version `10.1.3`
is possible that upgrade `akka-http` version?
or another solution?

many thanks

**Comment by doriordan** [comment]
skuber 2.6.1 now uses akka 10.2.4 so closing this
