### ISSUE TITLE
`access-token` and `expiry` fields must be optional for gcp auth provider

### ISSUE THREAD

**Issue by edio** [doriordan/skuber#301]
Currently _skuber_ fails if _access-token_ field is missing in `~/.kube/config`. This usally is the case for a newly initialized cluster.

**Steps to reproduce**:
1. obtain credentials for new k8s cluster with auth via GCP
```
export CLUSTER=...
export PROJECT=...
export REGION=...
gcloud beta container clusters get-credentials $CLUSTER --region $REGION --project $PROJECT
```
2. In Scala app that uses _skuber_ make a call to `skuber.k8sInit`

**Expected result**:
k8sInit call returns normally and your app connects to the newly configured cluster with credentials from `~/.kube/config`

**Actual result**:
k8sInit call fails with exception
```
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:529)
        at scala.None$.get(Option.scala:527)
        at skuber.api.Configuration$.valueAt$1(Configuration.scala:116)
        at skuber.api.Configuration$.authProviderRead$1(Configuration.scala:178)
        at skuber.api.Configuration$.toK8SAuthInfo$1(Configuration.scala:189)
        at skuber.api.Configuration$.$anonfun$parseKubeconfigStream$7(Configuration.scala:209)
        at skuber.api.Configuration$.$anonfun$parseKubeconfigStream$4(Configuration.scala:154)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
        at scala.collection.Iterator.foreach(Iterator.scala:941)
        at scala.collection.Iterator.foreach$(Iterator.scala:941)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
        at scala.collection.IterableLike.foreach(IterableLike.scala:74)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
        at scala.collection.TraversableLike.map(TraversableLike.scala:238)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at skuber.api.Configuration$.topLevelYamlToK8SConfigMap$1(Configuration.scala:154)
        at skuber.api.Configuration$.$anonfun$parseKubeconfigStream$1(Configuration.scala:209)
        at scala.util.Try$.apply(Try.scala:213)
        at skuber.api.Configuration$.parseKubeconfigStream(Configuration.scala:102)
        at skuber.api.Configuration$.$anonfun$parseKubeconfigFile$2(Configuration.scala:93)
        at scala.util.Success.flatMap(Try.scala:251)
        at skuber.api.Configuration$.parseKubeconfigFile(Configuration.scala:92)
        at skuber.api.Configuration$.$anonfun$defaultK8sConfig$3(Configuration.scala:308)
        at scala.util.Failure.orElse(Try.scala:224)
        at skuber.api.Configuration$.$anonfun$defaultK8sConfig$2(Configuration.scala:308)
        at scala.Option.getOrElse(Option.scala:189)
        at skuber.api.Configuration$.defaultK8sConfig(Configuration.scala:307)
```

_skuber_ already has the logic to correctly refresh tokens using GCP as auth provider, it is only a matter of making those fields in kubeconfig optional and adjusting all surrounding logic.

I'm willing to work on a PR for this.

**Comment by edio** [comment]
Fixed with #297
