### ISSUE TITLE
Scaling should respect the /apis vs /api path component

### ISSUE THREAD

**Issue by hollinwilkins** [doriordan/skuber#42]
Currently when scaling, the `forExtensionsAPI` is forced to false. This should be determined instead by the Kind type class passed to buildRequest.

Error because of this issue:
```
Request DefaultHttpRequest(chunked: false)
PUT /api/extensions/v1beta1/namespaces/default/deployments/testing-worker/scale HTTP/1.1
Content-Type: application/json
Content-Length: 127
Connection: keep-alive
Host: 192.168.64.2:8443
Accept: */*
User-Agent: AHC/1.0

Response DefaultHttpResponse(chunked: false)
HTTP/1.1 404 Not Found
Content-Type: application/json
Date: Thu, 06 Apr 2017 03:41:02 GMT
Content-Length: 174
```

The path should be:
```
/apis/extensions/v1beta1/namespaces/default/deployments/testing-worker/scale
```

**Comment by hollinwilkins** [comment]
This causes an internal server error when I change it to respect the API component, not sure what's up here:

```
Request DefaultHttpRequest(chunked: false)
PUT /apis/extensions/v1beta1/namespaces/default/deployments/testing-worker/scale HTTP/1.1
Content-Type: application/json
Content-Length: 127
Connection: keep-alive
Host: 192.168.64.2:8443
Accept: */*
User-Agent: AHC/1.0

Response DefaultHttpResponse(chunked: false)
HTTP/1.1 500 Internal Server Error
Content-Type: application/json
Date: Thu, 06 Apr 2017 03:45:12 GMT
Content-Length: 202

23:52:43.771 [New I/O worker #1] DEBUG com.ning.http.client.providers.netty.channel.ChannelManager - Adding key: https://192.168.64.2:8443 for channel [id: 0x20454afa, /192.168.64.1:59561 => /192.168.64.2:8443]
23:52:43.804 [ForkJoinPool-1-worker-13] WARN skuber.api - [Skuber Response: non-ok status returned = Status(v1,Status,ListMeta(,),Some(Failure),Some(an error on the server ("") has prevented the request from succeeding),Some(InternalError),Some({}),Some(500))
[error] (run-main-0) skuber.api.client.package$K8SException: Status(v1,Status,ListMeta(,),Some(Failure),Some(an error on the server ("") has prevented the request from succeeding),Some(InternalError),Some({}),Some(500))
skuber.api.client.package$K8SException: Status(v1,Status,ListMeta(,),Some(Failure),Some(an error on the server ("") has prevented the request from succeeding),Some(InternalError),Some({}),Some(500))
	at skuber.api.client.package$.checkResponseStatus(package.scala:371)
	at skuber.api.client.package$.toKubernetesResponse(package.scala:340)
	at skuber.ext.package$ExtensionsGroupAPI$$anonfun$executeScaleMethod$1.apply(package.scala:126)
	at skuber.ext.package$ExtensionsGroupAPI$$anonfun$executeScaleMethod$1.apply(package.scala:126)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by doriordan** [comment]
@hollinwilkins what version of Kubernetes are you testing against?

**Comment by doriordan** [comment]
This issue is not applicable to latest code, so closing
